### ISSUE TITLE
Breaking changes in librespot-java 1.0.0

### ISSUE THREAD

**Issue by devgianlu** [xMordax/ansible-role-librespot#2]
I've just released 1.0.0 which has a lot of breaking changes in the configuration file. I would create a PR for you, but I'm not sure what to change. The new configuration is [here](https://github.com/librespot-org/librespot-java/blob/master/core/src/main/resources/default.toml).

**Comment by xMordax** [comment]
Hey @devgianlu!

Thanks for the heads up, appreciate it!
I updated the my Ansible roles to match you current ```1.0.0``` release, the fix is in here 523b74b9a2be2cf6703c1cced94db4fd54692ad2.

If you ever feel like trying Ansible out, you can for sure create a PR on here, its a super simple YAML based language.
Currently my test are not completely automated with Travis, that is because I am testing my code in Vagrant boxes and Travis does not support Vagrant. With Docker you just cant test all functionalities that you develop in Ansible.
Therefore if you ever feel like testing Ansible out, install Molecule and Vagrant and make sure that ```librespot_installation_type``` variable is set to ```librespot-java```. This way Molecule with start up a empty VM and install Librespot-Java on it.
The code is pretty self explanatory, but just to explain in in a few words. All I do in the role for your project, I download it, build it, copy the jar to the server where I start the service so that I get the ```.toml``` file and afterwards go with regex and configure each of your config lines. Note, Ansible converts the code from YAML to Python, so all regex expressions are Python based.

Hope this helps ^^ But I am also happy to fix it myself.

Till next time!
